language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  global:
  - secure: "mE5g8IYDUcweIxv+hum2wM3tA5pYVHX0XkfSOX/eh21o4dbr/HJh+YCMwcd5nrFiQ1KpFb35bqZhokJJm1gg3mKUCVKpdxmYoViKW2v8ggkdeyA2sU6zHDKcGhqhNkqiyKmXRclvhjNLfWWAjLCmbWHF/55uRMMK+o4StuT7KR3mcAihLsdiwRL7uLwNou1msMXk10DHaIE3K1if+0cn9U7rAeVOJY1b+MxLtO3ayBRyLB4Ee92RggCsPcHj9WpHbdlfNtDE1wauHZuphDpB7NvBc4MVPwQXk+bS7AhAvjGBxYk4/kATZ5f9OUmRV2oQJdHY4bj73RTkynXJFVhBNd+obPhj0xbbgJFyCR5mFndRZ2iGoz624rFG2c5ImHiV7qAbfeEfqn5SVMzetr/mag4IRIlU0SjJyjrV71FuuYVSCqvPuQNB0PrOXbtgoc/omnriPY0e8+J6DZ9QwkUmwpD41he7thrZ4/6IBcy5fzBP3okWGjPYyMT8eLm2qwQGxhBkrzLl8PBkXfv3MFz7qnzszHsRLcIa+baNVNiPv7R8zelbsIvyg150FBsZT5k4TJsi6WrT/wao+S/Q9P8D4LMIMsHvoExGSpYE2RJ47WoW38dK5F6w0V6wWY/T4Xnt0lsz+YQG9xQvf3izuMsvH9O2EmyfzJAdQK6JXmGlkwU="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
